import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"
import { checkRateLimit, getCached, setCache, CACHE_KEYS, CACHE_TTL } from "@/lib/redis"

export async function POST(request: Request) {
  const supabase = await createClient()
  
  const { data: { user } } = await supabase.auth.getUser()
  
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  // Rate limiting with Redis
  const rateLimit = await checkRateLimit(user.id, "generate", 10, 60) // 10 requests per minute
  
  if (!rateLimit.allowed) {
    return NextResponse.json(
      { 
        error: "Rate limit exceeded",
        resetAt: rateLimit.resetAt,
        remaining: rateLimit.remaining 
      },
      { status: 429 }
    )
  }

  const { prompt, appId, appName } = await request.json()

  if (!prompt) {
    return NextResponse.json({ error: "Prompt is required" }, { status: 400 })
  }

  try {
    // Generate code (in production, call your AI model here)
    const generatedCode = `// Generated by Holy AI for ${appName || 'App'}
// Prompt: ${prompt}
import React from 'react';

export default function GeneratedComponent() {
  return (
    <div className="min-h-screen bg-background p-8">
      <h1 className="text-4xl font-bold mb-4">${appName || 'Generated App'}</h1>
      <div className="border border-border p-6 rounded-lg">
        <p className="text-muted-foreground">
          Generated based on: "${prompt}"
        </p>
      </div>
    </div>
  );
}
`

    // Save to database if appId provided
    if (appId && appId !== 'new') {
      await supabase
        .from('generated_apps')
        .update({
          generated_code: generatedCode,
          description: prompt,
          updated_at: new Date().toISOString()
        })
        .eq('id', appId)

      // Invalidate cache
      await setCache(CACHE_KEYS.appDetails(appId), null, 1)
    }

    // Cache the generated code
    if (appId) {
      await setCache(
        CACHE_KEYS.appDetails(appId),
        { code: generatedCode, generatedAt: new Date().toISOString() },
        CACHE_TTL.apps
      )
    }

    return NextResponse.json({
      success: true,
      code: generatedCode,
      remaining: rateLimit.remaining
    })
  } catch (error) {
    console.error("Generation error:", error)
    return NextResponse.json(
      { error: "Generation failed" },
      { status: 500 }
    )
  }
}

export async function GET(request: Request) {
  const supabase = await createClient()
  
  const { data: { user } } = await supabase.auth.getUser()
  
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const { searchParams } = new URL(request.url)
  const appId = searchParams.get("appId")

  if (!appId) {
    return NextResponse.json({ error: "App ID required" }, { status: 400 })
  }

  // Try cache first
  const cached = await getCached<{ code: string; generatedAt: string }>(
    CACHE_KEYS.appDetails(appId)
  )

  if (cached) {
    return NextResponse.json({ ...cached, fromCache: true })
  }

  // Fetch from database
  const { data: app, error } = await supabase
    .from('generated_apps')
    .select('generated_code, updated_at')
    .eq('id', appId)
    .single()

  if (error || !app) {
    return NextResponse.json({ error: "App not found" }, { status: 404 })
  }

  // Cache the result
  await setCache(
    CACHE_KEYS.appDetails(appId),
    { code: app.generated_code, generatedAt: app.updated_at },
    CACHE_TTL.apps
  )

  return NextResponse.json({
    code: app.generated_code,
    generatedAt: app.updated_at,
    fromCache: false
  })
}
